### PR TITLE
Cleaning up the house

### PR DESCRIPTION
**Pull request by alaxalves**
## Proposed Changes

Deleting unecessary scripts and changing scripts locations.

## Type of Changes

What type of change this Pull Request brings to Falko?
_Put an `x` in the boxes that apply_

- [x] Bugfix
- [ ] New Feature

## Checklist

_Put an `x` in the boxes that apply. If you're confused about any of the following topics, ask us. We're here to help you!_

- [x] This Pull Request has a significant name.
- [x] The build is okay (tests, code climate).
- [x] This Pull Request mentions a related issue.

### CODE REVIEW

**Comment by alaxalves** [comment]
Fixes #333 and #340

**Comment by cantuariavc** [comment]
@alaxalves, travis failed.

**Comment by cantuariavc** [comment]
"The command "yarn add coveralls" failed and exited with 1 during ." this is the Travis' message. Do you know what is it?

**Comment by alaxalves** [comment]
@cantuariavc I was trying to change npm to use yarn, but it seems more complicated than it looks so I have reverted the changes.

**Review by cantuariavc — APPROVED** [review]

**Pull request merged**
